const app = document.getElementById('app');
const workspace = document.getElementById('map-workspace');
const windowsLayer = document.getElementById('windows-layer');
const state = { theme: localStorage.getItem('geoai-theme') || 'dark', z: 20, windows: [], activeId: null, context: 'Satellite / AI', dock: 'Layers' };
const analysisList = ['Spectral Analysis','Change Detection','Explain Area','Spatial Feature Extraction','AI Insights','Parcel Inspector','Disaster Intelligence','Weather Intelligence','Layer Laboratory'];
const contexts = ['Satellite / AI','Urban Parcel','Disaster Intelligence','Weather Intelligence'];
const menuData = {
  file:[['New Workspace','Ctrl N'],['Open Workspace','Ctrl O'],['Save Workspace','Ctrl S'],['Save Workspace As',''],['sep'],['Import',''],['Export',''],['Recent Projects','›'],['sep'],['Exit','']],
  view:[['2D GIS','view:2d'],['3D Terrain','view:3d'],['Globe View','view:globe'],['sep'],['Layers','panel:Layers'],['Insights','panel:Insights'],['Features','panel:Features'],['Story','panel:Story'],['Inspector','dock:Inspector'],['sep'],['Cascade Windows','arrange:cascade'],['Tile Horizontally','arrange:horizontal'],['Tile Vertically','arrange:vertical'],['Stack Windows','arrange:stack'],['Minimize All','arrange:minimize'],['Reset Layout','arrange:reset'],['sep'],['Fullscreen','fullscreen'],['Show/Hide Timeline','timeline'],['Show/Hide Status Bar','status']],
  analysis:analysisList.map(x=>[x,`open:${x}`]),
  reports:[['Mission Brief','open:Mission'],['Story Builder','open:Story'],['Export Map Snapshot',''],['Generate Simulated Report','']]
};
function init(){
  setTheme(state.theme); renderContexts(); renderMenus(); renderDock(); bindStatic(); restoreWindows();
}
function setTheme(theme){ state.theme=theme; app.classList.toggle('theme-bright',theme==='bright'); app.classList.toggle('theme-dark',theme==='dark'); localStorage.setItem('geoai-theme',theme); }
function renderContexts(){ document.getElementById('contexts').innerHTML=contexts.map(c=>`<button class="context-chip ${c===state.context?'active':''}" data-context="${c}">${c}</button>`).join(''); }
function renderMenus(){ Object.entries(menuData).forEach(([name,items])=>{document.getElementById(`${name}-menu`).innerHTML=items.map(([label,action])=>label==='sep'?'<div class="menu-sep"></div>':`<button data-action="${action||''}" data-label="${label}">${label}<span>${action?.startsWith('view:')?'':action?.startsWith('arrange:')?'':action?.startsWith('open:')?'':' '+action}</span></button>`).join('');}); }
function bindStatic(){
  document.addEventListener('click', e=>{
    const trigger=e.target.closest('.menu-trigger');
    if(trigger){const open=trigger.classList.contains('open');document.querySelectorAll('.menu-trigger').forEach(x=>x.classList.remove('open'));document.querySelectorAll('.dropdown').forEach(x=>x.classList.remove('show'));if(!open){trigger.classList.add('open');document.getElementById(`${trigger.dataset.menu}-menu`).classList.add('show')}return}
    if(!e.target.closest('.menu-wrap')){document.querySelectorAll('.menu-trigger').forEach(x=>x.classList.remove('open'));document.querySelectorAll('.dropdown').forEach(x=>x.classList.remove('show'));}
    const action=e.target.closest('[data-action]')?.dataset.action; if(action) handleAction(action,e.target.closest('[data-action]').dataset.label);
    const opener=e.target.closest('[data-open]');if(opener)openWindow(opener.dataset.open);
    const context=e.target.closest('[data-context]');if(context){state.context=context.dataset.context;renderContexts(); updateContext();}
    const panel=e.target.closest('[data-panel]');if(panel){setDock(panel.dataset.panel);}
    const dock=e.target.closest('[data-dock]');if(dock){setDock(dock.dataset.dock);}
    const view=e.target.closest('[data-view]');if(view)setView(view.dataset.view);
  });
  document.getElementById('theme-toggle').onclick=()=>setTheme(state.theme==='dark'?'bright':'dark');
  document.getElementById('new-session').onclick=()=>openWindow('AI Insights');
  document.getElementById('left-collapse').onclick=()=>app.classList.toggle('collapsed-left');
  document.getElementById('right-collapse').onclick=()=>app.classList.toggle('collapsed-right');
  document.getElementById('timeline-hide').onclick=()=>app.classList.add('timeline-hidden');
  document.getElementById('timeline-show').onclick=()=>app.classList.remove('timeline-hidden');
  document.getElementById('legend-collapse').onclick=()=>document.getElementById('map-legend').classList.toggle('legend-collapsed');
  document.querySelector('.map-controls button:last-child').onclick=()=>app.classList.toggle('fullscreen-map');
  document.getElementById('time-range').oninput=e=>{document.getElementById('time-out').value=`14 Sep ${e.target.value}`};
  document.getElementById('play-btn').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='▶'?'❚❚':'▶'};
  document.querySelectorAll('.speed button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.speed button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
  document.addEventListener('keydown',keyHandler);
  setupDockResize(document.getElementById('left-resizer'),'left'); setupDockResize(document.getElementById('right-resizer'),'right'); setupToolbarDrag();
}
function handleAction(action,label){if(action.startsWith('open:'))openWindow(action.slice(5));else if(action.startsWith('view:'))setView(action.slice(5));else if(action.startsWith('panel:'))setDock(action.slice(6));else if(action.startsWith('dock:'))setDock(action.slice(5));else if(action.startsWith('arrange:'))arrange(action.slice(8));else if(action==='fullscreen')app.classList.toggle('fullscreen-map');else if(action==='timeline')app.classList.toggle('timeline-hidden');else if(action==='status')document.getElementById('status-bar').style.display=document.getElementById('status-bar').style.display==='none'?'flex':'none';else if(label==='New Workspace')openWindow('AI Insights');}
function keyHandler(e){const mod=e.ctrlKey||e.metaKey;if(e.key==='F3'){e.preventDefault();setTheme(state.theme==='dark'?'bright':'dark')}if(e.key==='Escape'&&state.activeId)closeWindow(state.activeId);if(mod&&e.key.toLowerCase()==='n'){e.preventDefault();openWindow('AI Insights')}if(mod&&e.key.toLowerCase()==='o'){e.preventDefault();openWindow('Layer Laboratory')}if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();flash('Workspace saved — demo state persisted')}if(mod&&e.shiftKey&&e.key.toLowerCase()==='w'&&state.activeId)minimizeWindow(state.activeId);}
function setView(view){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const map=document.getElementById('map');map.className=`map map-${view}`;flash(`${view==='2d'?'2D GIS':view==='3d'?'3D Terrain':'Globe View'} enabled`)}
function setDock(name){state.dock=name;document.querySelectorAll('[data-dock]').forEach(b=>b.classList.toggle('active',b.dataset.dock===name));document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));renderDock();}
function renderDock(){const details={Layers:`<h3>ACTIVE LAYERS</h3>${['Sentinel-2 · 14 Sep 2023','NDVI Vegetation Index','Flood Hazard Probability','Parcel Boundaries','Weather Anomaly'].map((x,i)=>`<label class="layer-row"><input type="checkbox" checked><i style="background:${['#779c6b','#65a16c','#6aa6c5','#d29a64','#997eba'][i]}"></i><span>${x}<small>SIMULATED DATA</small></span></label>`).join('')}`,Insights:`<h3>AI INSIGHTS</h3><div class="insight"><strong>Vegetation recovery detected</strong><p>+12.4% seasonal index gain inside the current AOI.</p></div><div class="insight"><strong>Water extent stable</strong><p>No significant anomaly against the 10-year baseline.</p></div>`,Features:`<h3>FEATURE SELECTION</h3><div class="insight"><strong>0 features selected</strong><p>Use Point, Rectangle, or Polygon tools to inspect map features.</p></div>`,Story:`<h3>STORYBOARD</h3><div class="insight"><strong>Ranchi Land Change 2023</strong><p>Five simulated scenes prepared for a mission briefing.</p></div><button class="compare" data-open="Story">Open Story Builder</button>`,Inspector:`<h3>MAP INSPECTOR</h3><div class="insight"><strong>Cursor coordinates</strong><p>23.3443° N<br>85.3096° E<br>Elevation: 628 m</p></div>`};document.getElementById('dock-content').innerHTML=details[state.dock];}
function updateContext(){const names={ 'Satellite / AI':'Sentinel-2 monitoring layers', 'Urban Parcel':'Cadastral parcel boundaries', 'Disaster Intelligence':'Flood and cyclone intelligence', 'Weather Intelligence':'Weather anomaly layers'};flash(`${state.context}: ${names[state.context]}`);setDock('Layers');}
function flash(message){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';Object.assign(el.style,{position:'absolute',zIndex:5000,bottom:'105px',left:'50%',transform:'translateX(-50%)',background:'#29332aeF',color:'#fff',padding:'7px 11px',border:'1px solid #81916d',boxShadow:'0 4px 12px #0007',fontSize:'11px'});document.body.append(el)}el.textContent=message;el.style.display='block';clearTimeout(el._t);el._t=setTimeout(()=>el.style.display='none',1800)}
function defaultWindow(title,index){const rect=workspace.getBoundingClientRect(),w=Math.min(430,Math.max(300,rect.width*.42)),h=Math.min(310,Math.max(200,rect.height*.48));return{id:`win-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,title,x:Math.max(20,Math.min(55+index*38,rect.width-w-20)),y:Math.max(50,Math.min(100+index*30,rect.height-h-25)),width:w,height:h,minWidth:260,minHeight:180,zIndex:++state.z,minimized:false,maximized:false,visible:true};}
function openWindow(title){let existing=state.windows.find(w=>w.title===title&&!w.visible);if(existing){existing.visible=true;existing.minimized=false;focusWindow(existing.id);renderWindows();return}const w=defaultWindow(title,state.windows.filter(x=>x.visible).length%6);state.windows.push(w);state.activeId=w.id;renderWindows();persist();}
function closeWindow(id){const w=state.windows.find(x=>x.id===id);if(w){w.visible=false;if(state.activeId===id)state.activeId=null;renderWindows();persist();}}
function focusWindow(id){const w=state.windows.find(x=>x.id===id);if(!w)return;state.activeId=id;w.zIndex=++state.z;renderWindows();persist();}
function minimizeWindow(id){const w=state.windows.find(x=>x.id===id);if(w){w.minimized=true;renderWindows();persist();}}
function maximizeWindow(id){const w=state.windows.find(x=>x.id===id);if(!w)return;const r=workspace.getBoundingClientRect();if(!w.maximized){w.restore={x:w.x,y:w.y,width:w.width,height:w.height};Object.assign(w,{x:8,y:42,width:r.width-16,height:r.height-50,maximized:true,minimized:false})}else{Object.assign(w,w.restore,{maximized:false});}focusWindow(id);renderWindows();persist();}
function renderWindows(){windowsLayer.innerHTML='';state.windows.filter(w=>w.visible).forEach(w=>{const el=document.createElement('section');el.className=`floating-window ${state.activeId===w.id?'active':''}`;el.dataset.id=w.id;el.style.cssText=`left:${w.x}px;top:${w.y}px;width:${w.width}px;height:${w.minimized?'29':w.height}px;z-index:${w.zIndex}`;el.innerHTML=`<div class="window-titlebar"><span class="drag-icon">≡</span><strong>${w.title}</strong><span class="demo">DEMO</span><span class="win-spacer"></span><button class="win-control" data-win="min" title="Minimize">—</button><button class="win-control" data-win="max" title="${w.maximized?'Restore':'Maximize'}">${w.maximized?'▣':'□'}</button><button class="win-control close" data-win="close" title="Close">×</button></div>${w.minimized?'':`<div class="window-body">${contentFor(w.title)}</div><i class="resize-handle n" data-resize="n"></i><i class="resize-handle s" data-resize="s"></i><i class="resize-handle e" data-resize="e"></i><i class="resize-handle w" data-resize="w"></i><i class="resize-handle ne" data-resize="ne"></i><i class="resize-handle nw" data-resize="nw"></i><i class="resize-handle se" data-resize="se"></i><i class="resize-handle sw" data-resize="sw"></i>`}`;el.onpointerdown=()=>focusWindow(w.id);el.querySelector('.window-titlebar').onpointerdown=e=>startDrag(e,w.id);el.querySelectorAll('[data-win]').forEach(b=>b.onclick=e=>{e.stopPropagation();const x=b.dataset.win;x==='close'?closeWindow(w.id):x==='min'?minimizeWindow(w.id):maximizeWindow(w.id)});el.querySelectorAll('[data-resize]').forEach(h=>h.onpointerdown=e=>startResize(e,w.id,h.dataset.resize));windowsLayer.append(el)});}
function contentFor(title){const type=title.toLowerCase();const val=type.includes('spectral')?'0.72':type.includes('change')?'+12.4%':type.includes('parcel')?'92.1%':type.includes('weather')?'28.6°C':'84.7%';const label=type.includes('spectral')?'NDVI MEAN':type.includes('change')?'NET CHANGE':type.includes('parcel')?'PARCEL MATCH':type.includes('weather')?'SURFACE TEMP':'CONFIDENCE';return `<div class="analysis-intro"><div><h4>${title}</h4><p>Current AOI · simulated analytic output</p></div><span class="tag">DEMO DATA</span></div><div class="metrics"><div class="metric"><small>${label}</small><b class="green">${val}</b></div><div class="metric"><small>AREA SAMPLED</small><b>142.5 km²</b></div><div class="metric"><small>SCENES</small><b class="orange">24</b></div></div><div class="chart"></div><div class="window-bottom"><span>Last updated: 14 Sep 2023</span><button class="compare">Export simulated result</button></div>`;}
function startDrag(e,id){if(e.target.closest('button'))return;const w=state.windows.find(x=>x.id===id);if(!w||w.maximized)return;e.preventDefault();focusWindow(id);const sx=e.clientX,sy=e.clientY,ox=w.x,oy=w.y;function move(ev){const r=workspace.getBoundingClientRect();let x=ox+ev.clientX-sx,y=oy+ev.clientY-sy;const snap=15;if(Math.abs(x)<snap)x=0;if(Math.abs(y-40)<snap)y=40;if(Math.abs((r.width-w.width)-x)<snap)x=r.width-w.width;if(Math.abs((r.height-w.height)-y)<snap)y=r.height-w.height;w.x=Math.max(0,Math.min(x,r.width-w.width));w.y=Math.max(40,Math.min(y,r.height-w.height));renderWindows()}function up(){window.removeEventListener('pointermove',move);persist()}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
function startResize(e,id,edge){e.preventDefault();e.stopPropagation();const w=state.windows.find(x=>x.id===id);if(!w||w.maximized)return;focusWindow(id);const sx=e.clientX,sy=e.clientY,start={x:w.x,y:w.y,width:w.width,height:w.height};function move(ev){let dx=ev.clientX-sx,dy=ev.clientY-sy;let x=start.x,y=start.y,width=start.width,height=start.height;if(edge.includes('e'))width=Math.max(w.minWidth,start.width+dx);if(edge.includes('s'))height=Math.max(w.minHeight,start.height+dy);if(edge.includes('w')){width=Math.max(w.minWidth,start.width-dx);x=start.x+(start.width-width)}if(edge.includes('n')){height=Math.max(w.minHeight,start.height-dy);y=start.y+(start.height-height)}const r=workspace.getBoundingClientRect();w.x=Math.max(0,x);w.y=Math.max(40,y);w.width=Math.min(width,r.width-w.x);w.height=Math.min(height,r.height-w.y);renderWindows()}function up(){window.removeEventListener('pointermove',move);persist()}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
function arrange(type){const ws=state.windows.filter(w=>w.visible);const r=workspace.getBoundingClientRect();if(type==='reset'){state.windows=[];state.activeId=null;renderWindows();persist();flash('Workspace layout reset');return}if(type==='minimize'){ws.forEach(w=>w.minimized=true);renderWindows();persist();return}ws.forEach(w=>w.minimized=false);if(type==='cascade'||type==='stack'){ws.forEach((w,i)=>Object.assign(w,{x:type==='stack'?30:30+i*34,y:type==='stack'?55:55+i*28,width:Math.min(430,r.width-60),height:Math.min(300,r.height-70),maximized:false}));}else if(type==='horizontal'){const h=Math.max(180,(r.height-55)/ws.length);ws.forEach((w,i)=>Object.assign(w,{x:8,y:42+i*h,width:r.width-16,height:h-5,maximized:false}));}else if(type==='vertical'){const width=Math.max(260,(r.width-16)/ws.length);ws.forEach((w,i)=>Object.assign(w,{x:8+i*width,y:42,width:width-5,height:r.height-50,maximized:false}));}renderWindows();persist();flash(`${type==='horizontal'?'Horizontally tiled':type==='vertical'?'Vertically tiled':type[0].toUpperCase()+type.slice(1)} windows`);}
function persist(){localStorage.setItem('geoai-windows',JSON.stringify(state.windows));}
function restoreWindows(){try{const stored=JSON.parse(localStorage.getItem('geoai-windows')||'[]');if(Array.isArray(stored)){state.windows=stored;state.z=Math.max(20,...stored.map(w=>w.zIndex||0));renderWindows()}}catch{}}
function setupDockResize(handle,side){let down=false,sx,initial;handle.addEventListener('pointerdown',e=>{down=true;sx=e.clientX;initial=side==='left'?document.getElementById('left-sidebar').getBoundingClientRect().width:document.getElementById('right-dock').getBoundingClientRect().width;handle.setPointerCapture(e.pointerId);handle.classList.add('active')});handle.addEventListener('pointermove',e=>{if(!down)return;let v=side==='left'?initial+e.clientX-sx:initial-e.clientX+sx;v=Math.max(180,Math.min(420,v));const area=document.querySelector('.work-area');if(side==='left')area.style.gridTemplateColumns=`${v}px 4px minmax(300px,1fr) 4px ${document.getElementById('right-dock').getBoundingClientRect().width}px`;else area.style.gridTemplateColumns=`${document.getElementById('left-sidebar').getBoundingClientRect().width}px 4px minmax(300px,1fr) 4px ${v}px`});handle.addEventListener('pointerup',()=>{down=false;handle.classList.remove('active')});}
function setupToolbarDrag(){const el=document.getElementById('map-toolbar');el.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;const startX=e.clientX,startY=e.clientY,rect=el.getBoundingClientRect(),parent=workspace.getBoundingClientRect();el.style.transform='none';el.style.left=`${rect.left-parent.left}px`;el.style.top=`${rect.top-parent.top}px`;function move(ev){el.style.left=`${Math.max(0,Math.min(parent.width-el.offsetWidth,rect.left-parent.left+ev.clientX-startX))}px`;el.style.top=`${Math.max(0,Math.min(parent.height-el.offsetHeight,rect.top-parent.top+ev.clientY-startY))}px`;}function up(){window.removeEventListener('pointermove',move)}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})});}
init();
